#!/bin/bash
#
# Script principal de build pour SaveTheDate
# Génère les binaires iOS (.ipa) et Android (.aab) pour un client donné
#
# Usage: ./build.sh <client_slug> [--ios-only|--android-only]
#
set -e

CLIENT_SLUG=$1
BUILD_TARGET=${2:-"all"}  # all, --ios-only, --android-only

if [ -z "$CLIENT_SLUG" ]; then
  echo "Usage: ./build.sh <client_slug> [--ios-only|--android-only]"
  echo ""
  echo "Examples:"
  echo "  ./build.sh sarah-david          # Build iOS + Android"
  echo "  ./build.sh sarah-david --ios-only"
  echo "  ./build.sh sarah-david --android-only"
  exit 1
fi

# Chemins
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLIENT_DIR="$PROJECT_ROOT/clients/$CLIENT_SLUG"
CONFIG_FILE="$CLIENT_DIR/config.json"
MOBILE_DIR="$PROJECT_ROOT/mobile"

# Vérifications
if [ ! -d "$CLIENT_DIR" ]; then
  echo "❌ Client directory not found: $CLIENT_DIR"
  exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ Config file not found: $CONFIG_FILE"
  exit 1
fi

# Vérifier que jq est installé
if ! command -v jq &> /dev/null; then
  echo "❌ jq is required. Install with: brew install jq"
  exit 1
fi

# Lire les variables depuis config.json
APP_NAME=$(jq -r '.branding.app_name // .title' "$CONFIG_FILE")
EVENT_ID=$(jq -r '.event_id' "$CONFIG_FILE")
API_URL=$(jq -r '.api_url // "https://api.oninvite.fr"' "$CONFIG_FILE")
BUNDLE_ID_BASE=$(echo "$CLIENT_SLUG" | tr '-' '' | tr '_' '')
BUNDLE_ID_IOS="fr.oninvite.${BUNDLE_ID_BASE}"
BUNDLE_ID_ANDROID="fr.oninvite.${BUNDLE_ID_BASE}"

echo "═════════════════════════════════════════════════════════════════"
echo "🔨 Oninvite Build Script"
echo "═══════════════════════════════════════════════════════════════"
echo "📱 App Name: $APP_NAME"
echo "🆔 Event ID: $EVENT_ID"
echo "📦 Bundle ID iOS: $BUNDLE_ID_IOS"
echo "📦 Bundle ID Android: $BUNDLE_ID_ANDROID"
echo "🌐 API URL: $API_URL"
echo "═══════════════════════════════════════════════════════════════"

# 1. Générer les icônes
echo ""
echo "📦 Step 1: Generating icons..."
if [ -f "$CLIENT_DIR/assets/icon_1024.png" ]; then
  "$PROJECT_ROOT/scripts/generate_icons.sh" "$CLIENT_SLUG"
else
  echo "⚠️  Icon not found, using default"
fi

# 2. Copier les assets
echo ""
echo "📦 Step 2: Copying assets..."
mkdir -p "$MOBILE_DIR/assets/client"

# Copier les assets du client
if [ -d "$CLIENT_DIR/assets" ]; then
  cp -r "$CLIENT_DIR/assets/"* "$MOBILE_DIR/assets/client/" 2>/dev/null || true
fi

# Copier la config
cp "$CONFIG_FILE" "$MOBILE_DIR/assets/client/config.json"

# 3. Créer le fichier d'environnement
echo ""
echo "⚙️  Step 3: Creating environment file..."
cat > "$MOBILE_DIR/.env.production" <<EOF
# Generated by build.sh for $CLIENT_SLUG
EVENT_ID=$EVENT_ID
API_BASE_URL=$API_URL
BUNDLE_ID_IOS=$BUNDLE_ID_IOS
BUNDLE_ID_ANDROID=$BUNDLE_ID_ANDROID
APP_NAME=$APP_NAME
CLIENT_SLUG=$CLIENT_SLUG
EOF

# 4. Mettre à jour app.json pour Expo
echo ""
echo "⚙️  Step 4: Updating app.json..."
cat > "$MOBILE_DIR/app.json" <<EOF
{
  "expo": {
    "name": "$APP_NAME",
    "slug": "savethedate-$CLIENT_SLUG",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/client/icon_1024.png",
    "splash": {
      "image": "./assets/client/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "$BUNDLE_ID_IOS",
      "supportsTablet": true,
      "buildNumber": "1"
    },
    "android": {
      "package": "$BUNDLE_ID_ANDROID",
      "versionCode": 1,
      "adaptiveIcon": {
        "foregroundImage": "./assets/client/icon_1024.png",
        "backgroundColor": "#ffffff"
      }
    },
    "plugins": [
      "expo-notifications"
    ],
    "extra": {
      "eventId": "$EVENT_ID",
      "apiUrl": "$API_URL",
      "eas": {
        "projectId": "your-eas-project-id"
      }
    }
  }
}
EOF

# 5. Build iOS
if [ "$BUILD_TARGET" != "--android-only" ]; then
  echo ""
  echo "🍎 Step 5: Building iOS..."
  
  if [[ "$OSTYPE" == "darwin"* ]]; then
    cd "$MOBILE_DIR"
    
    # Utiliser EAS Build ou fastlane
    if command -v eas &> /dev/null; then
      echo "Using EAS Build..."
      eas build --platform ios --profile production --non-interactive
    elif [ -d "ios/fastlane" ]; then
      echo "Using Fastlane..."
      cd ios
      bundle exec fastlane build_and_upload \
        app_name:"$APP_NAME" \
        bundle_id:"$BUNDLE_ID_IOS" \
        event_id:"$EVENT_ID"
      cd ..
    else
      echo "Building with expo..."
      npx expo build:ios --type archive --no-wait
    fi
    
    cd "$PROJECT_ROOT"
  else
    echo "⚠️  iOS build requires macOS. Skipping..."
  fi
fi

# 6. Build Android
if [ "$BUILD_TARGET" != "--ios-only" ]; then
  echo ""
  echo "🤖 Step 6: Building Android..."
  
  cd "$MOBILE_DIR"
  
  # Utiliser EAS Build ou fastlane
  if command -v eas &> /dev/null; then
    echo "Using EAS Build..."
    eas build --platform android --profile production --non-interactive
  elif [ -d "android/fastlane" ]; then
    echo "Using Fastlane..."
    cd android
    bundle exec fastlane build_and_upload \
      app_name:"$APP_NAME" \
      bundle_id:"$BUNDLE_ID_ANDROID" \
      event_id:"$EVENT_ID"
    cd ..
  else
    echo "Building with expo..."
    npx expo build:android --type app-bundle --no-wait
  fi
  
  cd "$PROJECT_ROOT"
fi

# 7. Générer QR code
echo ""
echo "📱 Step 7: Generating QR code..."
"$PROJECT_ROOT/scripts/generate_qr.sh" "$CLIENT_SLUG"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ Build complete for $APP_NAME"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Check build status in EAS or App Store Connect"
echo "  2. Review and submit for review"
echo "  3. QR code: $CLIENT_DIR/qr_code.png"
echo ""
